[package]
name = "vulpi-typer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im-rc = "15.1.0"
vulpi-storage = { path = "../vulpi-storage" }
vulpi-report = { path = "../vulpi-report" }