[workspace]

members = [
    "crates/vulpi-tests",
    "crates/vulpi-lexer",
    "crates/vulpi-location",
    "crates/vulpi-intern",
    "crates/vulpi-syntax",
    "crates/vulpi-report",
]

resolver = "1"
