[workspace]

members = [
    "crates/vulpi-tests",
    "crates/vulpi-lexer",
    "crates/vulpi-location",
    "crates/vulpi-intern",
    "crates/vulpi-syntax",
    "crates/vulpi-report",
    "crates/vulpi-vfs",
    "crates/vulpi-parser",

]

resolver = "1"
