[workspace]

members = [
    "crates/vulpi-parser",
    "crates/vulpi-location",
    "crates/vulpi-macros",
    "crates/vulpi-syntax",
    "crates/vulpi-build",
    "crates/vulpi-report",
    "crates/vulpi-storage",
    "crates/vulpi-resolver",
    "crates/vulpi-cli",
]

resolver = "1"