[package]
name = "vulpi-intern"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulpi-show = { path = "../vulpi-show" }

lazy_static = "1.4.0"

[features]
default = ["single-shot"]
single-shot = []
