[package]
name = "vulpi-vfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filetime = "0.2.22"
vulpi-location = { path = "../vulpi-location" }
vulpi-intern = { path = "../vulpi-intern" }
