[package]
name = "vulpi-location"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulpi-storage = { path = "../vulpi-storage" }
vulpi-show = { path = "../vulpi-show" }
